config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :task_lists, only: [:index, :show, :create, :update, :destroy] do
    resources :tasks
  end

  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :task_list
end

app/models/task_list.rb
class TaskList < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_email(@contact).deliver_now
      redirect_to root_path, notice: "Votre message a bien été envoyé."
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  def index
    @task_lists = TaskList.all
  end

  def new
    @task_list = TaskList.new
  end

  def create
    @task_list = TaskList.new(task_list_params)
    @task_list.user = current_user
    if @task_list.save
      redirect_to task_list_path(@task_list)
    else
      render :new, alert: "Une erreur s'est produite lors de la création de la liste."
    end
  end

  def show
    @task_list = TaskList.find(params[:id])
  end

  def destroy
    @task_list = TaskList.find(params[:id])
    if @task_list.destroy
      redirect_to task_lists_path, notice: "La liste a été supprimée avec succès."
    else
      redirect_to @task_list, alert: "Une erreur s'est produite lors de la suppression de la liste."
    end
  end

  private

  def task_list_params
    params.require(:task_list).permit(:user_id, :name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @task_list = TaskList.find(params[:task_list_id])
    @task = Task.new
  end

  def create
    @task_list = TaskList.find(params[:task_list_id])
    @task = @task_list.tasks.build(task_params)

    if @task.save
      redirect_to task_list_path(@task_list)
    else
      Rails.logger.error @task.errors.full_messages.inspect
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    Rails.logger.info "Suppression de la tâche"
    if @task.destroy
      redirect_to tasks_path, notice: "La tâche a été supprimée avec succès."
    else
      redirect_to @task_list, alert: "Une erreur s'est produite lors de la suppression de la tâche."
    end
  end

  def index
    @task_list = TaskList.find(params[:task_list_id])
    @tasks = @task_list.tasks
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:task_list_id, :titre, :détails, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <%= render "shared/form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SitePerso</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "turbo", type: "module" %> 

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>

  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-3">
  <div class="container">
    <h1>Clothilde Drouet </h1>
    <h1>Développeuse web Ruby on Rails, HTML, CSS...</h1>
  </div>
  <hr>
    <h2> Pour un site web simple et efficace </h2>
  <div class="container mt-3">
      <h3 id="top"> Localisation et disponibilité </h3>
        <ul>
        <li> Localisation : Annecy (Haute-Savoie) </li>
        <br>
        <li> Disponibilité : 3 jours par semaine </li>
        </ul>
  </div>
  <div class="container mt-3">
      <h3 id="top"> Prestations </h3>
        <ul>
          <li> Développement web fullstack : </li>
           <p> Création de site web sur Ruby on Rails avec HTML5, CSS3, Bootstrap et PostGreSQL</p>
          <li> Création de site vitrine : </li>
            <p> Création de site web vitrine pour présenter votre activité</p>
          <li> Référencement naturel : </li>
            <p> Optimisation du référencement naturel de votre site web en respectant les bonnes pratiques en back-office </p>
          <li> Rédaction SEO : </li>
            <p>Création de contenu écrit optimisé pour le référencement web</p>
          <li> Mes réalisations : </li>
            <p> <a href="https://www.parkbuddies.ch/" class="custom-link">Park Buddies </a> l'application qui met en lien les parents pour qu'ils ne s'ennuient plus jamais quand ils emmènent leur(s) enfant(s) au parc! </p>
            <p> Venez utiliser mon <%= link_to "créateur de tâches", task_lists_path, class: "custom-link-bottom" %> </p>
        </ul>
  </div>

  <div class="container mb-3">
    <h3 id="end"> Contact </h3>
      </div>
    <%= link_to "Prenez contact avec moi !", new_contact_path, class: "btn btn-success rounded-pill" %>
    <div class="container mt-3">
      </div>

 </div>

    <hr>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="footer">
    <div class="footer-links">
      <a href="https://github.com/Newtoc0de"><i class="fab fa-github"></i></a>
      <a href="https://www.linkedin.com/in/clothilde-drouet"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Ce site a été codé avec <i class="fas fa-heart"></i> par Clothilde Drouet
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
     <%= simple_form_for @contact, url: contacts_path do |f| %>
        <div class="mb-3">
          <%= f.label :name, "Nom" %>
          <%= f.text_field :name, class: "form-control custom-rounded" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, "Email" %>
          <%= f.email_field :email, placeholder:"votreemail@email.com", class: "form-control custom-rounded" %>
        </div>
        <div class="mb-3">
          <%= f.label :message, "Message" %>
          <%= f.text_area :message, placeholder:"Décrivez votre super projet de site web ou votre besoin" ,class: "form-control custom-rounded" %>
        </div>
        <div class="mb-3">
          <%= f.submit "Envoyer", class: "btn btn-success rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>


</div>

app/views/shared/_navbar.html.erb
<div class="container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse">
        <ul class="navbar-nav me-auto">
          <div class="div">
            <li class="nav-item">
                <%= link_to "Localisation", anchor:"top", class: "nav-link"%>
            </li>
          </div>
              <li class="nav-item">
                <%= link_to "Contact", class: "nav-link", anchor: "end" %>
              </li>
            </ul>
      </div>
    </div>
</div>

app/views/task_lists/_new_task_list_form.html.erb
<div class="container">
  <div class="container mt-3">
  <%= simple_form_for TaskList.new do |f| %>
  <div class="field mt-3">
  <%= f.label :name, "Nom de la liste", class:"form-control custom-rounded", style: "text-align: center;", id:"form-control-color" %>
   <div class="field mt-3 mb-3">
  <%= f.text_field :name, class:"form-control custom-rounded" %>
  </div>
  <%= f.submit "Créer votre liste", class: "btn btn-success rounded-pill mt-3" %>
<% end %>
  </div>
</div>

app/views/task_lists/index.html.erb
<div class="container">
  <div class="content">
<% if @task_lists.empty? %>
   <h2> Créez une liste de tâches puis les tâches qui s'y rapportent </h2><!-- Si aucune task_list n'existe, afficher le formulaire de création -->
  <%= render 'new_task_list_form' %>

<% else %>
  <!-- Si des task_lists existent, les afficher -->
  <h2>Listes de tâches existantes :</h2>
  <p> Cliquez sur la liste pour créer les tâches qui s'y rapportent </p>
  <ul>
    <% @task_lists.each do |task_list| %>
  <li class="custom-li">
    <%= link_to task_list.name, new_task_list_task_path(task_list_id: task_list.id) %>
    <%=  link_to "Delete", task_list_path(task_list), data: { turbo_method: :delete } %>
  </li>
<% end %>



  </ul>
  <div class="container">
    <p> Vous souhaitez ajouter une liste supplémentaire ? </p>
   <%= render 'new_task_list_form' %>
  </div>
<% end %>
    <hr>
  </div>
</div>

app/views/task_lists/show.html.erb
<div class="container">
  <% if @lists.present? %>
    <div class="row">
      <% @lists.each do |list| %>
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body text-center">
              <h5 class="card-title"><%= list.title %></h5>
              <!-- Ajouter l'icône "poubelle" avec un lien pour supprimer la liste -->
              <%= link_to "Destroy", list_path(list), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
                <i class="far fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  <% else %>
    <%= render "task_lists/new_task_list_form" %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <%= simple_form_for [@task_list, Task.new], url:task_list_tasks_path(@task_list)  do |f| %>
  <%= f.hidden_field :task_list_id, value: @task_list.id %>
    <div class="field mt-3">
      <%= f.label :titre, "Nom de la tâche", class: "form-control custom-rounded", style: "text-align: center;", id:"form-control-color" %>
      <div class="field mt-3 mb-3">
        <%= f.text_field :titre, class: "form-control custom-rounded" %>
      </div>
      <%= f.label :détails, class: "form-control custom-rounded", style: "text-align: center;", id:"form-control-color" %>
      </div>
      <div class="field mt-3 mb-3">
      <%= f.text_area :détails, class: "form-control custom-rounded" %>
    </div>
    <div class="field mt-3">
      <%= f.check_box :completed, class: "form-check-input" %>
    </div>
    <div class="field mt-3">
      <%= f.label :completed, class: "form-check-label" %>
    </div>
    <%= f.submit "Créer la tâche", class: "btn btn-success rounded-pill mt-3" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2> Voici la tache </h2>
  <div class="container">
    <h3> <%= @task.titre %> </h3>
    <div class="well"> <%= @task.détails %></div>
    <% if @task.completed %>
      <i class="fas fa-check-square"></i> C'est fait
    <% else %>
      <i class="far fa-square"></i> C'est encore à faire
       <% end %>
    <%= link_to "Supprimer la tâche", task_list_task_path(@task.task_list, @task), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cette tâche ?" } %>
  </div>
    <%= link_to "Retour à la liste", task_list_path(@task.task_list) %>
</div>